// <auto-generated />
using System;
using Battleships.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Battleships.Migrations
{
    [DbContext(typeof(GameResultContext))]
    [Migration("20221228215953_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Battleships.DAL.Entities.GameActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GameResultId")
                        .HasColumnType("int");

                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameResultId");

                    b.ToTable("Actions");
                });

            modelBuilder.Entity("Battleships.DAL.Entities.GameResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FirstPlayerHitCount")
                        .HasColumnType("int");

                    b.Property<string>("FirstPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInProgress")
                        .HasColumnType("bit");

                    b.Property<int>("RoundCount")
                        .HasColumnType("int");

                    b.Property<int>("SecondPlayerHitCount")
                        .HasColumnType("int");

                    b.Property<string>("SecondPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinnerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("Battleships.DAL.Entities.GameActions", b =>
                {
                    b.HasOne("Battleships.DAL.Entities.GameResult", "GameResult")
                        .WithMany("Actions")
                        .HasForeignKey("GameResultId");

                    b.Navigation("GameResult");
                });

            modelBuilder.Entity("Battleships.DAL.Entities.GameResult", b =>
                {
                    b.Navigation("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
